### ISSUE TITLE
DB: Fix quest 'Smoke Before Fire (31743)

### ISSUE THREAD

**Issue by zTerragor** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#114]
Reference:https://www.wowhead.com/quest=31743/smoke-before-fire

SQL Fix:
`update `creature` SET `position_x` = -132.0905, `position_y` = -1564.7851, `position_z` = 72.8406 WHERE `id` = 66301;`

**Comment by leelf00** [comment]
Is this from sniffs?

**Comment by zTerragor** [comment]
yes

**Comment by leelf00** [comment]
Ok.I merge into current DB.

**Comment by leelf00** [comment]
creature entry is 17350 ?

**Comment by zTerragor** [comment]
+

**Comment by leelf00** [comment]
I see the creature is on map 530.Quest is Pandaria.

**Comment by leelf00** [comment]
Guid 66301 's creature id is 17350.Reference wowhead https://www.wowhead.com/npc=17350/royal-blue-flutterer .Quest https://www.wowhead.com/quest=31743/smoke-before-fire is in Pandria.Maybe guid is wrong.
