### ISSUE TITLE
🐛 [Bug]server crash at loading

### ISSUE THREAD

**Issue by zTerragor** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#134]
server crash at loading
system Win10 64
Boost 1.69
OpenSSL 1.1.1s
`//=====================================================
Exception code: C0000005 ACCESS_VIOLATION
Fault address:  00007FF6E4E4D882 01:00000000018BC882 C:\Users\Максим\Desktop\RelWithDebInfo\ws\worldserver.exe

Registers:
RAX:0000000000000000
RBX:0000000000000000
RCX:000002A1BFD41040
RDX:000002A1BFCA2240
RSI:000002A1BFD902D0
RDI:000002A1BFC87060
R8: 0000000000000000
R9: 0000000000000080
R10:1A01A4C003ABD403
R11:000002A1BDBD45C8
R12:0000000000000000
R13:000002A1BFD41040
R14:00007FF6E51EE438
R15:000002A100000001
CS:RIP:0033:00007FF6E4E4D882
SS:RSP:002B:00000000C9B2F340  RBP:C9B2F3C0
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010206

Call stack:
Address   Frame     Function      SourceFile
00007FF6E4E4D882  000000C6C9B2F3E0  PreparedResultSet::PreparedResultSet+82  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\src\server\shared\Database\QueryResult.cpp line 46
00007FF6E4E5132A  000000C6C9B2F430  MySQLConnection::Query+9A  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\src\server\shared\Database\MySQLConnection.cpp line 458
00007FF6E36C47B6  000000C6C9B2F530  Master::_StartDB+12E6  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\src\server\worldserver\Master.cpp line 556
00007FF6E36C1686  000000C6C9B2F750  Master::Run+19F6  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\src\server\worldserver\Master.cpp line 204
00007FF6E36BA7B5  000000C6C9B2F7E0  ace_main_i+5C5  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\src\server\worldserver\Main.cpp line 153
00007FF6E36BAC86  000000C6C9B2F810  main+36  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\src\server\worldserver\Main.cpp line 76
00007FF6E4F939B0  000000C6C9B2F850  __scrt_common_main_seh+10C  D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl line 288
00007FFA8EBD74B4  000000C6C9B2F880  BaseThreadInitThunk+14
00007FFA8EFC26A1  000000C6C9B2F900  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFA8F00EEF4  000000C6C9B2D480  NtGetContextThread+14
00007FFA8C98DF7B  000000C6C9B2D4B0  GetThreadContext+B
00007FF6E36C88B7  000000C6C9B2D9E0  WheatyExceptionReport::printTracesForAllThreads+B7  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\src\server\shared\Debugging\WheatyExceptionReport.cpp line 405
00007FF6E36C7144  000000C6C9B2E070  WheatyExceptionReport::GenerateExceptionReport+314  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\src\server\shared\Debugging\WheatyExceptionReport.cpp line 504
00007FF6E36C7D44  000000C6C9B2E320  WheatyExceptionReport::WheatyUnhandledExceptionFilter+274  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\src\server\shared\Debugging\WheatyExceptionReport.cpp line 158
00007FFA8CA202E7  000000C6C9B2E440  UnhandledExceptionFilter+1E7
00007FFA8F015530  000000C6C9B2E480  memset+13B0
00007FFA8EFFC876  000000C6C9B2E4F0  __C_specific_handler+96
00007FFA8F01241F  000000C6C9B2E520  __chkstk+11F
00007FFA8EFC14A4  000000C6C9B2EC30  RtlRaiseException+434
00007FFA8F010F4E  000000C6C9B2F330  KiUserExceptionDispatcher+2E
00007FF6E4E4D882  000000C6C9B2F3E0  PreparedResultSet::PreparedResultSet+82  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\src\server\shared\Database\QueryResult.cpp line 46
00007FF6E4E5132A  000000C6C9B2F430  MySQLConnection::Query+9A  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\src\server\shared\Database\MySQLConnection.cpp line 458
00007FF6E36C47B6  000000C6C9B2F530  Master::_StartDB+12E6  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\src\server\worldserver\Master.cpp line 556
00007FF6E36C1686  000000C6C9B2F750  Master::Run+19F6  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\src\server\worldserver\Master.cpp line 204
00007FF6E36BA7B5  000000C6C9B2F7E0  ace_main_i+5C5  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\src\server\worldserver\Main.cpp line 153
00007FF6E36BAC86  000000C6C9B2F810  main+36  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\src\server\worldserver\Main.cpp line 76
00007FF6E4F939B0  000000C6C9B2F850  __scrt_common_main_seh+10C  D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl line 288
00007FFA8EBD74B4  000000C6C9B2F880  BaseThreadInitThunk+14
00007FFA8EFC26A1  000000C6C9B2F900  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFA8F010B14  000000C6C9EFF7C0  ZwWaitForWorkViaWorkerFactory+14
00007FFA8EFC2E17  000000C6C9EFFAC0  TpReleaseCleanupGroupMembers+747
00007FFA8EBD74B4  000000C6C9EFFAF0  BaseThreadInitThunk+14
00007FFA8EFC26A1  000000C6C9EFFB70  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFA8F010B14  000000C6C9FFF6D0  ZwWaitForWorkViaWorkerFactory+14
00007FFA8EFC2E17  000000C6C9FFF9D0  TpReleaseCleanupGroupMembers+747
00007FFA8EBD74B4  000000C6C9FFFA00  BaseThreadInitThunk+14
00007FFA8EFC26A1  000000C6C9FFFA80  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFA8F010B14  000000C6CA0FF940  ZwWaitForWorkViaWorkerFactory+14
00007FFA8EFC2E17  000000C6CA0FFC40  TpReleaseCleanupGroupMembers+747
00007FFA8EBD74B4  000000C6CA0FFC70  BaseThreadInitThunk+14
00007FFA8EFC26A1  000000C6CA0FFCF0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFA8F00D1E4  000000C6CA1FFBB0  NtRemoveIoCompletion+14
00007FFA8C96F22F  000000C6CA1FFC10  GetQueuedCompletionStatus+4F
00007FF6E4E607A1  000000C6CA1FFD00  boost::asio::detail::win_iocp_io_context::do_one+2A1  C:\local\boost_1_69_0\boost\asio\detail\impl\win_iocp_io_context.ipp line 381
00007FF6E4E61C08  000000C6CA1FFD70  boost::asio::io_context::run+B8  C:\local\boost_1_69_0\boost\asio\impl\io_context.ipp line 62
00007FF6E4F59F73  000000C6CA1FFDB0  ?system_category_message_win32@detail@system@boost@@YAPEBDHPEAD_K@Z+1F3
00007FFA8CF11BB2  000000C6CA1FFDE0  _configthreadlocale+92
00007FFA8EBD74B4  000000C6CA1FFE10  BaseThreadInitThunk+14
00007FFA8EFC26A1  000000C6CA1FFE90  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFA8F00D144  000000C6CA2FFB80  ZwWaitForSingleObject+14
00007FFA8C93306E  000000C6CA2FFC20  WaitForSingleObjectEx+8E
00007FFA4DD23B5F  000000C6CA2FFC60  ACE_OS::cond_wait+4F  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\OS_NS_Thread.cpp line 1765
00007FFA4DD2375B  000000C6CA2FFCF0  ACE_OS::cond_timedwait+2B  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\OS_NS_Thread.cpp line 1610
00007FFA4DCB1A2F  000000C6CA2FFD20  ACE_Message_Queue<ACE_MT_SYNCH,ACE_System_Time_Policy>::wait_not_empty_cond+3F  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\Message_Queue_T.cpp line 1776
00007FFA4DCA6F2D  000000C6CA2FFD60  ACE_Message_Queue<ACE_MT_SYNCH,ACE_System_Time_Policy>::dequeue_head+7D  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\Message_Queue_T.cpp line 1968
00007FFA4DCB726F  000000C6CA2FFD90  ACE_Activation_Queue::dequeue+1F  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\Activation_Queue.cpp line 89
00007FF6E4E63525  000000C6CA2FFDC0  DatabaseWorker::Run+15  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\src\server\shared\Database\DatabaseWorker.cpp line 44
00007FF6E4E63321  000000C6CA2FFDF0  std::thread::_Invoke<std::tuple<<lambda_5e98e289292c50a5872e3601a430a1b8> >,0>+11  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\thread line 56
00007FFA8CF11BB2  000000C6CA2FFE20  _configthreadlocale+92
00007FFA8EBD74B4  000000C6CA2FFE50  BaseThreadInitThunk+14
00007FFA8EFC26A1  000000C6CA2FFED0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFA8F00D144  000000C6CA3FFAF0  ZwWaitForSingleObject+14
00007FFA8C93306E  000000C6CA3FFB90  WaitForSingleObjectEx+8E
00007FFA4DD23B5F  000000C6CA3FFBD0  ACE_OS::cond_wait+4F  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\OS_NS_Thread.cpp line 1765
00007FFA4DD2375B  000000C6CA3FFC60  ACE_OS::cond_timedwait+2B  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\OS_NS_Thread.cpp line 1610
00007FFA4DCB1A2F  000000C6CA3FFC90  ACE_Message_Queue<ACE_MT_SYNCH,ACE_System_Time_Policy>::wait_not_empty_cond+3F  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\Message_Queue_T.cpp line 1776
00007FFA4DCA6F2D  000000C6CA3FFCD0  ACE_Message_Queue<ACE_MT_SYNCH,ACE_System_Time_Policy>::dequeue_head+7D  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\Message_Queue_T.cpp line 1968
00007FFA4DCB726F  000000C6CA3FFD00  ACE_Activation_Queue::dequeue+1F  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\Activation_Queue.cpp line 89
00007FF6E4E63525  000000C6CA3FFD30  DatabaseWorker::Run+15  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\src\server\shared\Database\DatabaseWorker.cpp line 44
00007FF6E4E63321  000000C6CA3FFD60  std::thread::_Invoke<std::tuple<<lambda_5e98e289292c50a5872e3601a430a1b8> >,0>+11  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\thread line 56
00007FFA8CF11BB2  000000C6CA3FFD90  _configthreadlocale+92
00007FFA8EBD74B4  000000C6CA3FFDC0  BaseThreadInitThunk+14
00007FFA8EFC26A1  000000C6CA3FFE40  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFA8F00D144  000000C6CA4FF540  ZwWaitForSingleObject+14
00007FFA8C93306E  000000C6CA4FF5E0  WaitForSingleObjectEx+8E
00007FFA4DD23B5F  000000C6CA4FF620  ACE_OS::cond_wait+4F  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\OS_NS_Thread.cpp line 1765
00007FFA4DD2375B  000000C6CA4FF6B0  ACE_OS::cond_timedwait+2B  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\OS_NS_Thread.cpp line 1610
00007FFA4DCB1A2F  000000C6CA4FF6E0  ACE_Message_Queue<ACE_MT_SYNCH,ACE_System_Time_Policy>::wait_not_empty_cond+3F  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\Message_Queue_T.cpp line 1776
00007FFA4DCA6F2D  000000C6CA4FF720  ACE_Message_Queue<ACE_MT_SYNCH,ACE_System_Time_Policy>::dequeue_head+7D  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\Message_Queue_T.cpp line 1968
00007FFA4DCB726F  000000C6CA4FF750  ACE_Activation_Queue::dequeue+1F  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\Activation_Queue.cpp line 89
00007FF6E4E63525  000000C6CA4FF780  DatabaseWorker::Run+15  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\src\server\shared\Database\DatabaseWorker.cpp line 44
00007FF6E4E63321  000000C6CA4FF7B0  std::thread::_Invoke<std::tuple<<lambda_5e98e289292c50a5872e3601a430a1b8> >,0>+11  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\thread line 56
00007FFA8CF11BB2  000000C6CA4FF7E0  _configthreadlocale+92
00007FFA8EBD74B4  000000C6CA4FF810  BaseThreadInitThunk+14
00007FFA8EFC26A1  000000C6CA4FF890  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFA8F00D144  000000C6CA5FFC50  ZwWaitForSingleObject+14
00007FFA8C93306E  000000C6CA5FFCF0  WaitForSingleObjectEx+8E
00007FFA4DD23B5F  000000C6CA5FFD30  ACE_OS::cond_wait+4F  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\OS_NS_Thread.cpp line 1765
00007FFA4DD2375B  000000C6CA5FFDC0  ACE_OS::cond_timedwait+2B  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\OS_NS_Thread.cpp line 1610
00007FFA4DCB1A2F  000000C6CA5FFDF0  ACE_Message_Queue<ACE_MT_SYNCH,ACE_System_Time_Policy>::wait_not_empty_cond+3F  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\Message_Queue_T.cpp line 1776
00007FFA4DCA6F2D  000000C6CA5FFE30  ACE_Message_Queue<ACE_MT_SYNCH,ACE_System_Time_Policy>::dequeue_head+7D  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\Message_Queue_T.cpp line 1968
00007FFA4DCB726F  000000C6CA5FFE60  ACE_Activation_Queue::dequeue+1F  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\Activation_Queue.cpp line 89
00007FF6E4E63525  000000C6CA5FFE90  DatabaseWorker::Run+15  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\src\server\shared\Database\DatabaseWorker.cpp line 44
00007FF6E4E63321  000000C6CA5FFEC0  std::thread::_Invoke<std::tuple<<lambda_5e98e289292c50a5872e3601a430a1b8> >,0>+11  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\thread line 56
00007FFA8CF11BB2  000000C6CA5FFEF0  _configthreadlocale+92
00007FFA8EBD74B4  000000C6CA5FFF20  BaseThreadInitThunk+14
00007FFA8EFC26A1  000000C6CA5FFFA0  RtlUserThreadStart+21

Call stack:
Address   Frame     Function      SourceFile
00007FFA8F00D144  000000C6CA6FF9C0  ZwWaitForSingleObject+14
00007FFA8C93306E  000000C6CA6FFA60  WaitForSingleObjectEx+8E
00007FFA4DD23B5F  000000C6CA6FFAA0  ACE_OS::cond_wait+4F  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\OS_NS_Thread.cpp line 1765
00007FFA4DD2375B  000000C6CA6FFB30  ACE_OS::cond_timedwait+2B  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\OS_NS_Thread.cpp line 1610
00007FFA4DCB1A2F  000000C6CA6FFB60  ACE_Message_Queue<ACE_MT_SYNCH,ACE_System_Time_Policy>::wait_not_empty_cond+3F  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\Message_Queue_T.cpp line 1776
00007FFA4DCA6F2D  000000C6CA6FFBA0  ACE_Message_Queue<ACE_MT_SYNCH,ACE_System_Time_Policy>::dequeue_head+7D  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\Message_Queue_T.cpp line 1968
00007FFA4DCB726F  000000C6CA6FFBD0  ACE_Activation_Queue::dequeue+1F  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\dep\acelite\ace\Activation_Queue.cpp line 89
00007FF6E4E63525  000000C6CA6FFC00  DatabaseWorker::Run+15  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\src\server\shared\Database\DatabaseWorker.cpp line 44
00007FF6E4E63321  000000C6CA6FFC30  std::thread::_Invoke<std::tuple<<lambda_5e98e289292c50a5872e3601a430a1b8> >,0>+11  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\thread line 56
00007FFA8CF11BB2  000000C6CA6FFC60  _configthreadlocale+92
00007FFA8EBD74B4  000000C6CA6FFC90  BaseThreadInitThunk+14
00007FFA8EFC26A1  000000C6CA6FFD10  RtlUserThreadStart+21
========================
Local Variables And Parameters

Call stack:
Address   Frame     Function      SourceFile
00007FF6E4E4D882  000000C6C9B2F3E0  PreparedResultSet::PreparedResultSet+82  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\src\server\shared\Database\QueryResult.cpp line 46
	Local  <user defined> 'this'
	Local  <user defined> 'this'
	Parameter  unsigned int 'fieldCount'
punting on symbol field
punting on symbol i
punting on symbol size
punting on symbol fIndex

00007FF6E4E5132A  000000C6C9B2F430  MySQLConnection::Query+9A  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\src\server\shared\Database\MySQLConnection.cpp line 458
	Local  unsigned int 'rowCount'
	Local  <user defined> 'result'
	Local  unsigned int 'fieldCount'

00007FF6E36C47B6  000000C6C9B2F530  Master::_StartDB+12E6  C:\Users\Максим\Documents\GitHub\Legends-of-Azeroth-Pandaria-5.4.8\src\server\worldserver\Master.cpp line 556
`

**Comment by leelf00** [comment]
Always crash or random crash on startup?

**Comment by zTerragor** [comment]
fix it on mysql 8  https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/commit/d16f9b71d1213e7937b7a231794ee7e3daaa122d
