### ISSUE TITLE
Fix creature damage on creatures -  57384,57382,57387,57388,57386,57333

### ISSUE THREAD

**Issue by zTerragor** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#136]
### Description

Fix creature damage on creatures -  57384,57382,57387,57388,57386,57333

### SQL fix

```sql
UPDATE `creature_template` SET `dmg_multiplier`= 1, `mindmg`=4328, `maxdmg`=7359 WHERE `entry` in (57384,57382,57387,57388,57386,57333);
```

### Branch

master

**Comment by leelf00** [comment]
https://www.wowhead.com/npc=57382/dark-globule#abilities;mode:h25

**Comment by leelf00** [comment]
Mark as hackfix.I remember these creatures only deal spell damage.

**Comment by leelf00** [comment]
68bce94950973f6111aa97052123c8f986590787
