### ISSUE TITLE
Custom scripts wont work

### ISSUE THREAD

**Issue by zTerragor** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#140]
### Description

All custom scripts wont work

### Expected behaviour

All custom scripts wont work

### Steps to reproduce the problem

1. compile source
2. setup server
3. run it
4. log in to game

Some scripts, such as - solocraft not work

### Branch

master

### Operating system

Windows 10 x64, 

### Custom changes

none

**Comment by leelf00** [comment]
https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/commit/371aad29953e0e11be66810cc01eec68c3260f35    fix solocraft
