### ISSUE TITLE
can't apply update on WORLD_DB 2023-05-27

### ISSUE THREAD

**Issue by baran2k** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#146]
### Description

i can't apply update on WORLD_DB 2023-05-27

### Expected behaviour

as it is written here
![image](https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/assets/35866104/6f0d65f2-4118-4eb3-9910-abdbb0699322)

i give errors

[0038]_world_custom.sql
ERROR 1146 (42S02) at line 13: Table 'world.locales_npc_text' doesn't exist

2023_04_08_world_footman_rob_scripts.sql
ERROR 1062 (23000) at line 118: Duplicate entry '114713' for key 'creature_formations.PRIMARY'

2023_07_08_world.sql
ERROR 1054 (42S22) at line 3: Unknown column 'menu_id' in 'where clause'

![image](https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/assets/35866104/94bb0c3e-792a-42ef-9b1d-d199694ef838)

Maybe I missed something else?

### Steps to reproduce the problem

1. create db "world"
2. upload dump world_548_20230527 to db "world"
3. try to upload updates ...
4. got an error

### Branch

master

### TC rev. hash/commit

master

### Operating system

windows 11

### Custom changes

no

**Comment by leelf00** [comment]
Use the full DB file on Release page.Do not apply other file in update folder.All patch SQL has already apply in the latest full DB.

**Comment by baran2k** [comment]
it's just that the update dates are later than the base ... and I thought that I needed update to get the newest world
