### ISSUE TITLE
🐛 [Bug]Report to Lanthan Perilon This task point NPC does not have any dialogue, please fix it, thank you

### ISSUE THREAD

**Issue by hua445633972** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#148]
![image](https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/assets/118568889/d3ca7376-7409-4850-bf49-405f71fbf6d6)
Report to “ Lanthan Perilon “ This task point NPC does not have any dialogue, please fix it, thank you

**Comment by Cagzwow** [comment]
UPDATE world.broadcast_text SET Text='Farewell to you, and may our ancestors be with you always!' WHERE ID=7785;
UPDATE world.broadcast_text SET Text='Hail, traveler! What brings you to my doorstep?' WHERE ID=7868;
UPDATE world.broadcast_text SET Text='I'm afraid I have nothing to teach to someone with your experience. But you haven't reached the end of the road yet. Speak to Lucan Cordell, behind the counter there. He'll guide you through the next phase of your journey.' WHERE ID=7869;
REPLACE INTO conditions (SourceTypeOrReferenceId,SourceGroup,SourceEntry,SourceId,ElseGroup,ConditionTypeOrReference,ConditionTarget,ConditionValue1,ConditionValue2,ConditionValue3,NegativeCondition,ErrorType,ErrorTextId,ScriptName,Comment) VALUES
(14,6570,7785,0,0,47,0,8327,74,0,0,0,0,'',"Group 0: Show gossip text 7785 if quest 'Report to Lanthan Perilon' is taken or completed or rewarded"),
(14,6570,7868,0,0,47,0,8327,1,0,0,0,0,'',"Group 0: Show gossip text 7868 if quest 'Report to Lanthan Perilon' is not taken"),
(14,6570,7869,0,0,8,0,8335,0,0,0,0,0,'',"Group 0: Show gossip text 7869 if quest 'Felendren the Banished' is rewarded");

Greets Lyucid

**Comment by hua445633972** [comment]
It's fixed, thank you very much

**Comment by hua445633972** [comment]
UPDATE world.broadcast_text SET Text='Farewell to you, and may our ancestors be with you always!' WHERE ID=7785;
UPDATE world.broadcast_text SET Text='Hail, traveler! What brings you to my doorstep?' WHERE ID=7868;
UPDATE world.broadcast_text SET Text='I'm afraid I have nothing to teach to someone with your experience. But you haven't reached the end of the road yet. Speak to Lucan Cordell, behind the counter there. He'll guide you through the next phase of your journey.' WHERE ID=7869;
REPLACE INTO conditions (SourceTypeOrReferenceId,SourceGroup,SourceEntry,SourceId,ElseGroup,ConditionTypeOrReference,ConditionTarget,ConditionValue1,ConditionValue2,ConditionValue3,NegativeCondition,ErrorType,ErrorTextId,ScriptName,Comment) VALUES
(14,6570,7785,0,0,47,0,8327,74,0,0,0,0,'',"Group 0: Show gossip text 7785 if quest 'Report to Lanthan Perilon' is taken or completed or rewarded"),
(14,6570,7868,0,0,47,0,8327,1,0,0,0,0,'',"Group 0: Show gossip text 7868 if quest 'Report to Lanthan Perilon' is not taken"),
(14,6570,7869,0,0,8,0,8335,0,0,0,0,0,'',"Group 0: Show gossip text 7869 if quest 'Felendren the Banished' is rewarded");

**Comment by leelf00** [comment]
Broadcast_text already has correct text,Missing Part is conditions.

**Comment by leelf00** [comment]
https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/commit/4804843824e23f6e7f9ff81bad9c76925d02fc1c

**Comment by leelf00** [comment]
https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/commit/4804843824e23f6e7f9ff81bad9c76925d02fc1c
