### ISSUE TITLE
🐛 [Bug] Broken Dungeon Finder

### ISSUE THREAD

**Issue by Nexon99** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#152]
## 🐛 Bug report
- Does not display the correct number of players in the queue (tested without another players).

### Expected behavior
https://www.zupimages.net/up/23/33/4d59.jpg

### Steps to reproduce
1. Choose a dungeon or raid
2. Watch the queue

### Version
  - 5.4.8.18414

**Comment by leelf00** [comment]
What is the correct number of the picture?

**Comment by Nexon99** [comment]
> What is the correct number of the picture?

I'm alone (local test).

**Comment by fuzionproject** [comment]
i know

**Comment by leelf00** [comment]
Try latest commit
