### ISSUE TITLE
Eve of Acherus🐛 [Bug]

### ISSUE THREAD

**Issue by zTerragor** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#154]
![image](https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/assets/81566364/bb69d588-e611-4508-85e0-2300499df47c)

**Comment by zTerragor** [comment]
create DK. some quests dont work. Such as eve  of Archerus

**Comment by zTerragor** [comment]
![image](https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/assets/81566364/581bd2a2-8eb3-4b37-870d-a23cb549db3a)

**Comment by zTerragor** [comment]
![image](https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/assets/81566364/0f1caf15-4319-4da4-93cb-5ef1d7037039)

**Comment by zTerragor** [comment]
Death Knight quest "Death from Above" # 12641 is not allowing control over the spawned Eye of Acherus.
if you try and move it resets and leaves your char in a state that you can not move. a re-log does clear the frozen player.
There does not seem to be any way to progress past this point as the purple portal behind the Lich King does not transport player to lower level.

Steps to reproduce
build fresh server
create death knight.
.quest add 12641
Click on Eye of Acherus control mechanism
sadness

**Comment by leelf00** [comment]
Scripts is not correct apply on gameobject.I saw it's commented.

**Comment by fuzionproject** [comment]
I know is the most Bug quest on all servers

**Comment by leelf00** [comment]
Not fixed

**Comment by zTerragor** [comment]
After this quest worked ,,,,on anther char dont work...strange
