### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Dude100** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#194]
### Description

How to update database from azerothcore to 

### SQL fix

```sql
need some help
```

### Branch

master

**Comment by leelf00** [comment]
We are not azerothcore

**Comment by Dude100** [comment]
Ofc but i want to update AC database for this core

**Comment by leelf00** [comment]
AC database is based on 3.3.5.Most world changed.
