### ISSUE TITLE
🐛 [Bug] Aysa of the Tushui (29410)

### ISSUE THREAD

**Issue by SandfieldGG** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#197]
## 🐛 Bug report

- After finishing the previous mission by defeating Jaomin Ro, Master Shang Xi will complete it and give us the next one, we will just have to go and complete it by talking to the merchant Lorvo. When you want to complete it, it does not show a dialog box or give any action.

### Expected behavior

- Complete mision with Merchant Lorvo and get the next one.

### Steps to reproduce

1. Get the quest Aysa of the Tushui with the Master Shang Xi (29410)
2. Go to Merchant Lorvo 
5. Mission cant complete.

### Version

Client Version: 
- 5.4.8.18414

**Comment by leelf00** [comment]
I cannot reproduce.Do you use latest full db?

**Comment by SandfieldGG** [comment]
Thats correct i used latest db upload here.

**Comment by leelf00** [comment]
Wait,I will create a clean char to test.

**Comment by leelf00** [comment]
https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/releases/download/WORLD_DB/world_548_20231122.7z  Or https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/releases/download/WDB/23.11.2023_WorldDB_Full.sql?

**Comment by SandfieldGG** [comment]
23.11.2023 world db

**Comment by leelf00** [comment]
Try the 1st one.i will check the second one

**Comment by SandfieldGG** [comment]
1st DB 22.11.2023 dont work the quest cant complete.

**Comment by zTerragor** [comment]
thus quest dont work on any db. It be fixed next  time

**Comment by leelf00** [comment]
![图片](https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/assets/25166407/acff0308-0420-4ba3-84c0-9ac6676caf84)

**Comment by leelf00** [comment]
@SandfieldGG This quest?

**Comment by SandfieldGG** [comment]
Correct

**Comment by leelf00** [comment]
I will export full world db again.I cannot reproduce on my worldserver.Maybe some thing missing when apply db.

**Comment by SandfieldGG** [comment]
23.11.2023? with the updates after that date?

**Comment by leelf00** [comment]
Try https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/releases/download/WORLD_DB/world_548_20231212.7z

**Comment by SandfieldGG** [comment]
Work with the new DB.
