### ISSUE TITLE
🐛 [Bug] Whisper when logging in

### ISSUE THREAD

**Issue by SandfieldGG** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#199]
## 🐛 Bug report

- When you enter the game you automatically receive an auto whisper

### Expected behavior

- Such a whisper should not come out

### Steps to reproduce

1. Create a character
2. Enter into the kingdom

### Version

Client Version: 
- 5.4.8.18414

**Comment by leelf00** [comment]
What is whisper text?

**Comment by SandfieldGG** [comment]
dont remember . or empty message

**Comment by icedcolor** [comment]
@leelf00   
![0)2UT4EO$~44PAQ{L)047$S](https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/assets/19793341/c950938a-d33e-4828-bd65-920ea996b903)

每次登录会有这样的悄悄话，切换场景也是。

**Comment by leelf00** [comment]
@icedcolor  Thank you for reply.I will debug it.

**Comment by leelf00** [comment]
@icedcolor windows build with eluna ?

**Comment by icedcolor** [comment]
@leelf00  Yes, with eluna ?

**Comment by leelf00** [comment]
I cannot reproduce with eluna off.So I guess you turn on eluna.

**Comment by icedcolor** [comment]
But I compiled with elun turned off.
Same with logging into the game or switching scenes.

**Comment by leelf00** [comment]
@icedcolor Try turn off solocraft or lfg solo to ensure if this message still show. Or try change to enUS language to ensure if this still happen.

**Comment by icedcolor** [comment]
@leelf00   I turned off SOLOCRAFT and LFGSolo and it's still the same, I don't have an US client, but it's the same with the TW client. I don't know where the problem is.

**Comment by leelf00** [comment]
@icedcolor Do you disable all game client addon?

**Comment by leelf00** [comment]
@icedcolor I will try to find the problem.

**Comment by leelf00** [comment]
@icedcolor Have you seen Game Event annouce in game?

**Comment by icedcolor** [comment]
@leelf00 
Event.Announce = 1 or 0 ，it's all the same.

**Comment by leelf00** [comment]
I tested lastest master source with zhTW client.I cannot reproduce when change map or player login.Is this happen randomly?

**Comment by icedcolor** [comment]
![FKL30(_H( FYB00SF 0%C](https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/assets/19793341/e0681be6-9e2b-4152-b092-df024f153f8a)

This is what my login shows
Don't understand what these numbers mean.

**Comment by leelf00** [comment]
@icedcolor Can you show all texts after player login for me?

**Comment by leelf00** [comment]
Please import full db on release page.

**Comment by icedcolor** [comment]
@leelf00 
I download the packaged version of this--Development Build(2024-01-13)
and I imported the SQL  WORLD_DB_2023-12-30
It's still the same.

It should be a database patch issue.
