### ISSUE TITLE
DB: archived scripts reprocessed ?

### ISSUE THREAD

**Issue by IvanLlanas** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#204]
### Description

On starting authserver for the first time an error pops out.
Files in "sql/updates/master/auth/old" are being processed when they should not, or they should not be there.

### Expected behaviour

authserver should start with no error.

### Steps to reproduce the problem

I populated the auth and characters databases with the scripts in directory "sql/base" and the world database with the script in [world_548_20231230.7z](https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/releases/download/WDB20231230/world_548_20231230.7z).

And on launching authserver:
```
Updating Auth database...
Duplicate filename "/home/ivan/mop/sources/sql/updates/master/auth/old/2023_11_10_auth.sql" occurred. 
Because updates are ordered by their filenames, every name needs to be unique!
Could not update the Login database, see log for details.
```
And the server aborts.
I removed the file and the same error is produced again but with another of the files in the directory:
```
-rw-rw-r-- 1 ivan ivan  205 Jan 11 19:08 2021_03_27_BattlePay_DP.sql
-rw-rw-r-- 1 ivan ivan  480 Jan 11 19:08 2021_03_27_BattlePay_log.sql
-rw-rw-r-- 1 ivan ivan  431 Jan 11 19:08 2021_03_27_WowTokens_log.sql
-rw-rw-r-- 1 ivan ivan  139 Jan 11 19:08 2021_05_15_Reinicio_de_Arenas.sql
-rw-rw-r-- 1 ivan ivan  343 Jan 11 19:08 2021_07_17_00_autobroadcast.sql
-rw-rw-r-- 1 ivan ivan  828 Jan 11 19:08 2021_08_08_Bonus_BG.sql
-rw-rw-r-- 1 ivan ivan 3222 Jan 11 19:08 2021_08_08_Config.sql
-rw-rw-r-- 1 ivan ivan   67 Jan 11 19:08 2023_11_03_auth.sql
-rw-rw-r-- 1 ivan ivan  278 Jan 11 19:08 2023_11_09_auth.sql
-rw-rw-r-- 1 ivan ivan  174 Jan 11 19:08 2023_11_10_auth.sql
-rw-rw-r-- 1 ivan ivan 8312 Jan 11 19:08 2023_11_26_auth.sql
-rw-rw-r-- 1 ivan ivan  277 Jan 11 19:08 2023_11_27_auth.sql
-rw-rw-r-- 1 ivan ivan 1452 Jan 11 19:08 2023_12_04_auth.sql
-rw-rw-r-- 1 ivan ivan 1053 Jan 11 19:08 fusion-cms.sql
```
When the last of these files is removed authserver starts normally.

After inspecting the contents of these files in the "old" directory they seem to be already added to the base/auth.sql

```
mysql> select * from updates;
Empty set (0.00 sec)

mysql> select * from sql_update;
Empty set (0.00 sec)

mysql> select * from updates_include;
+-------------------------------+----------+
| path                          | state    |
+-------------------------------+----------+
| $/sql/updates/master/auth     | RELEASED |
| $/sql/updates/master/auth/old | ARCHIVED |
+-------------------------------+----------+
2 rows in set (0.00 sec)
```

I guess those files should be removed from this directory in the github repository or make authserver not use the files in the "ARCHIVED" directories.

### Branch

master

### TC rev. hash/commit

522d84d

### Operating system

Ubuntu 23.04

### Custom changes

None.

**Comment by leelf00** [comment]
Disable AutoUpdate in config file.This function not work correctly.

**Comment by IvanLlanas** [comment]
I guess it is set variable `Updates.EnableDatabases = 0` in authserver.conf **and** worldserver.conf.
**It worked!**

There are a bunch of preset variables in config files which should be commented.
In fact authserver is complaining about `BanExpiryCheckInterval` being undefined but there is not an entry in the authserver.conf.dist file.
The same for `Arena.SeasonReward.Cleanup.Enabled`in worldserver.conf.dist.
