### ISSUE TITLE
DB: world_548_20231230.sql should not create a database

### ISSUE THREAD

**Issue by IvanLlanas** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#205]
### Description

Release [WORLD_DB_2023-12-30](https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/releases/download/WDB20231230/world_548_20231230.7z) contains the "world_548_20231230.sql" script whose first line is:
```
CREATE DATABASE `world_548` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin */ /*!80016 DEFAULT ENCRYPTION='N' */;
```

### SQL fix

```sql
Remove the database creation.
```

### Branch

master

### TC rev. hash/commit

522d84d

**Comment by leelf00** [comment]
Fixed

**Comment by zTerragor** [comment]
Norm work with mysql 8.34 on win 10 system
