### ISSUE TITLE
DB: MariaDB can be used by only changing one collation

### ISSUE THREAD

**Issue by IvanLlanas** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#206]
### Description

I installed and compiled the servers in an Ubuntu 23.04, replacing the MySQL database server with a MariaDB one.
I had to replace packages `mysql-server` and `libmysqlclient-dev` with `mariadb-server`, `mariadb-client`, `libmariadb-dev` and `libmariadb-dev-compat`.
It worked perfectly.
The only problem has been the SQL script "sql/base/auth.sql", which uses `utf8mb4_0900_ai_ci` collation which is not available in MariaDB.
I replaced all the appearances of `utf8mb4_0900_ai_ci` with `utf8mb4_unicode_520_ci` (I don't know about their equivalence, I just relied on "Google Search" for this).
```
cd ~/mop/sources/sql/base
cp auth.sql auth.sql.backup
sed -i 's/utf8mb4_0900_ai_ci/utf8mb4_unicode_520_ci/g' auth.sql 
```
After importing it to the auth database the servers works perfectly.

**So, it would be interesting to replace the use of `utf8mb4_0900_ai_ci` in "auth.sql" with another collation available in both engines, p.e. `utf8mb4_unicode_520_ci`, to give the user more options on the database engine.**

### SQL fix

```sql
Replace all appearances of "utf8mb4_0900_ai_ci" with "utf8mb4_unicode_520_ci" in "sql/base/auth.sql".
```

### Branch

master

### TC rev. hash/commit

522d84d

**Comment by leelf00** [comment]
Does Maria db support utf8mb4_bin？

**Comment by IvanLlanas** [comment]
So does the documentation say.
https://mariadb.com/kb/en/supported-character-sets-and-collations/
https://mariadb.com/docs/skysql-dbaas/ref/xpand/collations/utf8mb4_bin/

**Comment by leelf00** [comment]
Thanks
