### ISSUE TITLE
login client bug

### ISSUE THREAD

**Issue by jorge990125** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#213]
When I try to login it disconnects me and shows me the following error
ProcessIncoming: Client not authed opcode = 0
![imagen](https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/assets/66186993/4695b26c-fbe4-459a-b681-b906616fd5b3)

**Comment by leelf00** [comment]
This maybe occured after logout account.CMSG_AUTH_CONTINUED_SESSION has not implmented now.

**Comment by leelf00** [comment]
This problem can reproduce every time when login?

**Comment by jorge990125** [comment]
Yes, every time I log in it gives the same problem.

**Comment by leelf00** [comment]
This problem occur on windows platorm?

**Comment by jorge990125** [comment]
yes

**Comment by leelf00** [comment]
Do you use development version on release page build by bot?

**Comment by jorge990125** [comment]
no, I cloned the repository and compiled it myself

**Comment by leelf00** [comment]
This works on linux.I will debug windows version tonight.Thanks

**Comment by leelf00** [comment]
@jorge990125 Try it after commit 1b1015265e4d668d2574b83ae839027c1c74d789

**Comment by icedcolor** [comment]
@leelf00   The new submission is still the same.

**Comment by leelf00** [comment]
Ok,I will debug it again

**Comment by leelf00** [comment]
@jorge990125 @icedcolor try after commit de92df788637475be092b783435220e4713a9cff

**Comment by jorge990125** [comment]
When I come home from work I'll try it and let you know if it gives any errors.

**Comment by jorge990125** [comment]
@leelf00 It works perfect

**Comment by jorge990125** [comment]
How can I remove this whisper every time I connect it shows it to me?
![imagen](https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/assets/66186993/a8189ce2-2c34-497e-a765-42dd6c5e4c6c)

**Comment by kuramajssken001** [comment]
world.cpp

/*if (player)
        sendInfo(player);
    else
    {
        for (auto&& itr : sWorld->GetAllSessions())
            if (Player* plr = itr.second->GetPlayer())
                sendInfo(plr);
    }*/

**Comment by kuramajssken001** [comment]
@jorge990125 That'll do it.

**Comment by kuramajssken001** [comment]
@leelf00 ProcessIncoming: Client not authed opcode = 0
After my repeated testing, the problem persists. Still need to fix it .

**Comment by leelf00** [comment]
Thanks for information. Do you compile on windows or linux? @kuramajssken001

**Comment by zTerragor** [comment]
Normal compiling on win

**Comment by leelf00** [comment]
Ok.I will continue to debug it.

**Comment by leelf00** [comment]
> world.cpp
> 
> /_if (player) sendInfo(player); else { for (auto&& itr : sWorld->GetAllSessions()) if (Player_ plr = itr.second->GetPlayer()) sendInfo(plr); }*/

Line 4370.This maybe sendinfo when queue LFG.

**Comment by kuramajssken001** [comment]
> Thanks for information. Do you compile on windows or linux? @kuramajssken001

win 10 @leelf00

**Comment by leelf00** [comment]
@kuramajssken001 @icedcolor @zTerragor Try after commit 78ece5faa6d64fc782d65d8a1809463e34676ce9

**Comment by icedcolor** [comment]
![17](https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/assets/19793341/f87909af-1a5e-4b24-8d33-f0796c3644d8)
clone again and use win10，still the same.

**Comment by leelf00** [comment]
Thanks for information.I will debug again.

**Comment by wosergame** [comment]
> ![17](https://private-user-images.githubusercontent.com/19793341/309431328-f87909af-1a5e-4b24-8d33-f0796c3644d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzOTg5NjksIm5iZiI6MTcwOTM5ODY2OSwicGF0aCI6Ii8xOTc5MzM0MS8zMDk0MzEzMjgtZjg3OTA5YWYtMWE1ZS00YjI0LThkMzMtZjA3OTZjMzY0NGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDE2NTc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NzBkNWUwZjdmYWQ3NzRiYjM2ZWZkN2RhZjk5ZGNmOGMwZmFlODAzYjVhMzcwZGIzNmQ3ZThiNjk5NGQ1NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cRBswa6nN46qIpZDCROB6jbIVOTjOxw4gAjylYLL48M) clone again and use win10，still the same.

+1, does not work

**Comment by wosergame** [comment]
> ![17](https://private-user-images.githubusercontent.com/19793341/309431328-f87909af-1a5e-4b24-8d33-f0796c3644d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0ODk5MDYsIm5iZiI6MTcwOTQ4OTYwNiwicGF0aCI6Ii8xOTc5MzM0MS8zMDk0MzEzMjgtZjg3OTA5YWYtMWE1ZS00YjI0LThkMzMtZjA3OTZjMzY0NGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDE4MTMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNDIwM2ViMDFiNjVlNzZjNDE1NGVkNmUxMWM1YTBmMTliZTdmODUxMzk1MTVhODRjZTc0ZTI5NTdiNmYxODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1nADfD73bt16mysNpQaKldxYm-uVCnPeXpL4-iQ1-UQ) clone again and use win10，still the same.

+1, does not work on win :(

**Comment by leewheel** [comment]
I also have this problem, but sometimes he is good, which is very strange

**Comment by wosergame** [comment]
> I also have this problem, but sometimes he is good, which is very strange

authserver does not start?

**Comment by leewheel** [comment]
> > I also have this problem, but sometimes he is good, which is very strange
> 
> authserver does not start?

no it's... it's working perfectly

**Comment by wosergame** [comment]
> > > I also have this problem, but sometimes he is good, which is very strange
> > 
> > 
> > authserver does not start?
> 
> no it's... it's working perfectly

I don't have worldserver running yet - authserver is not workingI don't have worldserver running yet - authserver is not working

**Comment by leelf00** [comment]
> I also have this problem, but sometimes he is good, which is very strange

Happen every time on account login?

**Comment by leelf00** [comment]
@icedcolor @wosergame try latest commit.

**Comment by wosergame** [comment]
> @icedcolor @wosergame try latest commit.

disconnect from server :(

**Comment by wosergame** [comment]
> @icedcolor @wosergame try latest commit.

Client not authed opcode = 0, disconnect from server :(

**Comment by wosergame** [comment]
> @icedcolor @wosergame try latest commit.

Client not authed opcode = 0, disconnect from server :(

**Comment by leelf00** [comment]
@icedcolor @wosergame try latest commit again.

**Comment by leelf00** [comment]
Some bug after dungeon finish,maybe only effect when you enable lfgsolo.

**Comment by wosergame** [comment]
![image](https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/assets/78369752/792e7c5c-594a-4b14-b623-728d22af4180)
remained

**Comment by leelf00** [comment]
@wosergame Try set loggin level to debug and trace.And send me log.

**Comment by wosergame** [comment]
> @wosergame Try set loggin level to debug and trace.And send me log.

Compilation in debug returns an error.
bin\Debug\worldserver.exe : fatal error LNK1120: 1 unresolved externals

**Comment by leelf00** [comment]
set logger level in worldserver.conf.

**Comment by wosergame** [comment]
> set logger level in worldserver.conf.

I didn't quite get it, \src\server\worldserver.conf.dist here?

**Comment by leelf00** [comment]
Yes. Change Logger.root to 2.

**Comment by wosergame** [comment]
> Yes. Change Logger.root to 2.

[Uploading Server.log…]()

**Comment by leelf00** [comment]
No Client not authed found in Server.log

**Comment by wosergame** [comment]
> No Client not authed found in Server.log

so we're going back to the opcode error? :)

**Comment by leelf00** [comment]
Do you met  "Client not authed" login error? Other error?

**Comment by wosergame** [comment]
> Do you met "Client not authed" login error? Other error?

I do not understand what is the reason for turning off the server when passing dungeons :(

**Comment by leelf00** [comment]
@wosergame try latest commit

**Comment by acgogo2023** [comment]
Thank you for your efforts, but I am still encountering the same issue. I have already updated the code.

**Comment by leelf00** [comment]
Last commit fix the lfg solo crash bug,not login bug.

**Comment by wosergame** [comment]
> @wosergame try latest commit

it works, thanks, but the stats stack up when entering the dungeon several times and do not fall off when exiting the dungeon

**Comment by leelf00** [comment]
> > @wosergame try latest commit
> 
> it works, thanks, but the stats stack up when entering the dungeon several times and do not fall off when exiting the dungeon

Do you enable lfg solo?

**Comment by wosergame** [comment]
> Do you enable lfg solo?

yes

**Comment by leelf00** [comment]
When I set Logger.root=1,Console Server in worldserver.conf.,ProcessIncoming: Client not authed opcode = 0 disapperared

**Comment by wosergame** [comment]
> > > @wosergame try latest commit
> > 
> > 
> > it works, thanks, but the stats stack up when entering the dungeon several times and do not fall off when exiting the dungeon
> 
> Do you enable lfg solo?

I meant that after the character leaves the dungeon, the stats do not return to their nominal value, but continue to multiply

**Comment by leelf00** [comment]
@jorge990125 @wosergame @leewheel @kuramajssken001 Try last commit.This problem maybe fixed.

**Comment by kuramajssken001** [comment]
okay,thank u @leelf00
