### ISSUE TITLE
🐛 [Bug] Enable the eluna Compilation Errors 

### ISSUE THREAD

**Issue by icedcolor** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#218]
![PN 8G2M`SA6EGF{ZZ(JW(}P](https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/assets/19793341/cfac78c0-cea0-4833-a018-896e8df51ca6)

Enable the eluna   error

Disable the eluna Everything is fine.

**Comment by leelf00** [comment]
Ok.I will debug it

**Comment by acgogo2023** [comment]
Thank you for your efforts 
I'm also looking into this issue. By the way, I'd like to ask if the scripts in the “src/server/scripts/Custom” directory can be used normally. After summoning NPC900000, he couldn't assist me in teleporting to the destination.
Thank you again
