### ISSUE TITLE
As soon as the character goes online, or the character switches maps, it will automatically whisper.

### ISSUE THREAD

**Issue by ddk2001** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#221]
### Description

As soon as the character goes online, or the character switches maps, it will automatically whisper.
![Uploading GQ1`ZW)K`4D3VALO1U$F$8F.png…]()

### Expected behaviour

no

### Steps to reproduce the problem

no

### Branch

master

### TC rev. hash/commit

no

### Operating system

Windows 10 x64

### Custom changes

no

**Comment by leelf00** [comment]
From which commmit?

**Comment by ddk2001** [comment]
Sorry, forgot to fill in the commit code。The commit code is 00b81e0

**Comment by leelf00** [comment]
Trun off eluna and solocraft then take a screenshot for me.

**Comment by ddk2001** [comment]
The cause of the problem has been found, and it is caused by the plugin.
