### ISSUE TITLE
started MMAP Cont load

### ISSUE THREAD

**Issue by MOPandaria** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#222]
### Description

Could not load MMAP name:Outland, id:530, x:31, y:31 (mmap rep.: x:31, y:31)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0530_31_32.mmtile'

### Expected behaviour

MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/1064_32_32.mmtile'
Could not load MMAP name:Mogu Island Daily Area, id:1064, x:32, y:32 (mmap rep.: x:32, y:32)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/1064_31_32.mmtile'
Could not load MMAP name:Mogu Island Daily Area, id:1064, x:31, y:32 (mmap rep.: x:31, y:32)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/1064_31_31.mmtile'
Could not load MMAP name:Mogu Island Daily Area, id:1064, x:31, y:31 (mmap rep.: x:31, y:31)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/1064_32_31.mmtile'
Could not load MMAP name:Mogu Island Daily Area, id:1064, x:32, y:31 (mmap rep.: x:32, y:31)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0571_32_32.mmtile'
Could not load MMAP name:Northrend, id:571, x:32, y:32 (mmap rep.: x:32, y:32)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0571_31_32.mmtile'
Could not load MMAP name:Northrend, id:571, x:31, y:32 (mmap rep.: x:31, y:32)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0571_31_31.mmtile'
Could not load MMAP name:Northrend, id:571, x:31, y:31 (mmap rep.: x:31, y:31)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0571_32_31.mmtile'
Could not load MMAP name:Northrend, id:571, x:32, y:31 (mmap rep.: x:32, y:31)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0000_48_27.mmtile'
Could not load MMAP name:Eastern Kingdoms, id:0, x:48, y:27 (mmap rep.: x:48, y:27)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0530_32_32.mmtile'
Could not load MMAP name:Outland, id:530, x:32, y:32 (mmap rep.: x:32, y:32)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0530_31_31.mmtile'
Could not load MMAP name:Outland, id:530, x:31, y:31 (mmap rep.: x:31, y:31)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0530_31_32.mmtile'
Could not load MMAP name:Outland, id:530, x:31, y:32 (mmap rep.: x:31, y:32)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0000_46_21.mmtile'
Could not load MMAP name:Eastern Kingdoms, id:0, x:46, y:21 (mmap rep.: x:46, y:21)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0571_28_27.mmtile'
Could not load MMAP name:Northrend, id:571, x:28, y:27 (mmap rep.: x:28, y:27)

### Steps to reproduce the problem

./worldserver 

### Branch

master

### TC rev. hash/commit

LastCommit

### Operating system

Debian

### Custom changes

NO

**Comment by leelf00** [comment]
Reextract mmaps can solve part of the problem.

**Comment by cTrinity** [comment]
Yes, I did it and still tip

> Reextract mmaps can solve part of the problem.

Yes, I did it and still prompted

**Comment by MOPandaria** [comment]
> Reextract mmaps can solve part of the problem.

Yes, I did it and still tip

**Comment by MOPandaria** [comment]
> Reextract mmaps can solve part of the problem.

There are still prompts，

**Comment by MOPandaria** [comment]
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0571_31_32.mmtile'
Could not load MMAP name:Northrend, id:571, x:31, y:32 (mmap rep.: x:31, y:32)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0000_35_44.mmtile'
Could not load MMAP name:Eastern Kingdoms, id:0, x:35, y:44 (mmap rep.: x:35, y:44)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0000_36_45.mmtile'
Could not load MMAP name:Eastern Kingdoms, id:0, x:36, y:45 (mmap rep.: x:36, y:45)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0000_37_45.mmtile'
Could not load MMAP name:Eastern Kingdoms, id:0, x:37, y:45 (mmap rep.: x:37, y:45)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0530_32_32.mmtile'
Could not load MMAP name:Outland, id:530, x:32, y:32 (mmap rep.: x:32, y:32)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0530_31_31.mmtile'
Could not load MMAP name:Outland, id:530, x:31, y:31 (mmap rep.: x:31, y:31)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0530_31_32.mmtile'
Could not load MMAP name:Outland, id:530, x:31, y:32 (mmap rep.: x:31, y:32)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0001_39_44.mmtile'
Could not load MMAP name:Kalimdor, id:1, x:39, y:44 (mmap rep.: x:39, y:44)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0571_28_27.mmtile'
Could not load MMAP name:Northrend, id:571, x:28, y:27 (mmap rep.: x:28, y:27)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0571_28_26.mmtile'
Could not load MMAP name:Northrend, id:571, x:28, y:26 (mmap rep.: x:28, y:26)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0571_31_31.mmtile'
Could not load MMAP name:Northrend, id:571, x:31, y:31 (mmap rep.: x:31, y:31)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0000_46_21.mmtile'
Could not load MMAP name:Eastern Kingdoms, id:0, x:46, y:21 (mmap rep.: x:46, y:21)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0000_48_27.mmtile'
Could not load MMAP name:Eastern Kingdoms, id:0, x:48, y:27 (mmap rep.: x:48, y:27)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0571_28_28.mmtile'
Could not load MMAP name:Northrend, id:571, x:28, y:28 (mmap rep.: x:28, y:28)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0571_28_29.mmtile'
Could not load MMAP name:Northrend, id:571, x:28, y:29 (mmap rep.: x:28, y:29)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0571_32_32.mmtile'
Could not load MMAP name:Northrend, id:571, x:32, y:32 (mmap rep.: x:32, y:32)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0571_31_32.mmtile'
Could not load MMAP name:Northrend, id:571, x:31, y:32 (mmap rep.: x:31, y:32)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0571_31_31.mmtile'
Could not load MMAP name:Northrend, id:571, x:31, y:31 (mmap rep.: x:31, y:31)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0571_32_31.mmtile'
Could not load MMAP name:Northrend, id:571, x:32, y:31 (mmap rep.: x:32, y:31)
MMAP:loadMap: Could not open mmtile file '../../Data/mmaps/0000_35_42.mmtile'
Could not load MMAP name:Eastern Kingdoms, id:0, x:35, y:42 (mmap rep.: x:35, y:42)

Worldserver keeps running and keeps reporting that no player is online

**Comment by leelf00** [comment]
Yes.I notice this.Before this commit the problem still exists. I just delete ignore warning condition of this.

**Comment by icedcolor** [comment]
The current MMAPS don't seem to be working, for example, monsters ignore paths.

**Comment by leelf00** [comment]
I found current mmaps disable liquid check。

**Comment by jasongdove** [comment]
This has to do with the transport system.
