### ISSUE TITLE
the boss of Icecrown Fortress, Sarufar。

### ISSUE THREAD

**Issue by ddk2001** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#230]
### Description

Before the boss of Icecrown Fortress, Sarufar, there was no reaction after the conversation.

### Expected behaviour

The next boss cannot be played

### Steps to reproduce the problem

no 

### Branch

master

### TC rev. hash/commit

any

### Operating system

Windows 10 x64

### Custom changes

no

**Comment by leelf00** [comment]
Aliance or Horde side?

**Comment by ddk2001** [comment]
I tested it with the Alliance

**Comment by leelf00** [comment]
boss 3 gunboat should skip when solocraft

**Comment by leelf00** [comment]
boss_deathbringer_saurfang seems missing somthing

**Comment by ddk2001** [comment]
Even if you skip the gunboat, the boss behind you will not be able to continue to pass.

**Comment by ddk2001** [comment]
Horde can open the boss smoothly

**Comment by leelf00** [comment]
Okay.I wiil compare the diff

**Comment by leelf00** [comment]
high_overlord_saurfang and muradin_bronzebeard share same guid. Update creature not dymatic load script correctly.

**Comment by ddk2001** [comment]
What mode of Linux do you use to compile it? You can see detailed crash logs. I compiled in vs2022's RelWithDebInfo mode. Still don't see detailed crash logs.

**Comment by leelf00** [comment]
I always conpile with Debug mode when debuging somethings.

**Comment by ddk2001** [comment]
I didn't expect to fix a script that required so many file changes

**Comment by leelf00** [comment]
This is not script error.It's core logic error.PR is still WIP, not pass test.
