### ISSUE TITLE
About mmaps 🐛 [Bug]

### ISSUE THREAD

**Issue by icedcolor** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#233]
Automatically shuts down when the mmaps prompt appears after starting worldserver.
It's a new extracted map file.
![QQ图片20240523142419](https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/assets/19793341/bc046c87-31f2-44f1-85f9-441f4d4a64bd)

**Comment by leelf00** [comment]
Can you post full log after server startup before crash?

**Comment by icedcolor** [comment]
@leelf00 

[Archive_worldserver.exe_[23-5_22-50-52].txt](https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/files/15418612/Archive_worldserver.exe_.23-5_22-50-52.txt)
[Archive_worldserver.exe_[23-5_22-37-49].txt](https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/files/15418614/Archive_worldserver.exe_.23-5_22-37-49.txt)

**Comment by icedcolor** [comment]
[Archive_worldserver.exe_[23-5_23-5-19].txt](https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/files/15418799/Archive_worldserver.exe_.23-5_23-5-19.txt)

**Comment by leelf00** [comment]
Before player login?

**Comment by icedcolor** [comment]
Sometimes it's the start-up process, sometimes it's the gameing.

**Comment by Core002** [comment]
Can confirm, mmaps eventually crashes worldserver sometime after startup

**Comment by Yuukiring** [comment]
me too，Did you solve it?

**Comment by Yuukiring** [comment]
I think the issue might be caused by extracting the map files using the Chinese client. It may be necessary to extract the map files using the English client instead.

**Comment by leelf00** [comment]
No. This maybe not an issue or maybe something mismatch in code.

**Comment by Yuukiring** [comment]
> No. This maybe not an issue or maybe something mismatch in code.

Can you share an extracted data file using this platform https://www.mediafire.com/?

**Comment by zTerragor** [comment]
No problem with ru client .some file if you want , i upload files on media fire. 

I return to dev to :)

**Comment by Yuukiring** [comment]
> No problem with ru client .some file if you want , i upload files on media fire.
> 
> I return to dev to :)
thank u，waiting for u

**Comment by icedcolor** [comment]
#248     No more errors after this fix

**Comment by leelf00** [comment]
[(https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/commit/1aeb4b8e112894885bebc42d21be2186504c3f00)](https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/commit/1aeb4b8e112894885bebc42d21be2186504c3f00)

**Comment by acgogo2023** [comment]
> #248 No more errors after this fix

need new extracted map file ?

**Comment by acgogo2023** [comment]
> Ok

Could you please share it to your 'data' folder?
