### ISSUE TITLE
Spell/Rogue: Combat Readiness [Talent]

### ISSUE THREAD

**Issue by Core002** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#234]
## 🐛 Bug report

- Combat Readiness does not drop aura after 10 seconds of no incoming melee attacks.

### Expected behavior

- After 10 seconds, combat readiness should drop from player if no melee attacks on him were performed.

### Steps to reproduce

1.  Use Combat Readiness with no creature/player meleeing you.
2. After 10 seconds, the spell continues the full 20 second duration.
3.
4. ...
5. Profit.

### Version

Client Version: 
- 5.4.8 18414

**Comment by leelf00** [comment]
Fixed by https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/pull/304
