### ISSUE TITLE
What are the requirements for installing Ubuntu 24.04 deployment, and what are the steps for SQL import

### ISSUE THREAD

**Issue by xiaochenshuma** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#244]
### Description

What are the requirements for installing Ubuntu 24.04 deployment, and what are the steps for SQL import

### SQL fix

```sql
What are the requirements for installing Ubuntu 24.04 deployment, and what are the steps for SQL import
```

### Branch

master

### TC rev. hash/commit

What are the requirements for installing Ubuntu 24.04 deployment, and what are the steps for SQL import

**Comment by leelf00** [comment]
https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/blob/master/.github/workflows/linux_gcc.yml
