### ISSUE TITLE
The 'Core/Map] Remove CurrentMap hack' caused the server to crash

### ISSUE THREAD

**Issue by ctmwow** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#302]
This submission accidentally removed some IsTemporary judgments
“IsTemporary” is used for judging the Stampede for hunter
now， After casting the Stampede, the server crashes

**Comment by leelf00** [comment]
Stampede (hunter talent)?

**Comment by 5840174** [comment]
hunter spell 121818
HUNTER_SPELL_GLYPH_OF_STAMPEDE 57902

**Comment by leelf00** [comment]
I cannot reproduce crash. Is server crashed when on worldmap or raidmap?

**Comment by jasongdove** [comment]
I can reproduce the crash; use `.additem 43356` and learn and apply the glyph first.
