### ISSUE TITLE
NpcAddCommand is incomplete

### ISSUE THREAD

**Issue by 5840174** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#314]
when use command .npc add *
the creature is unable to display
re login to the game
all nearby creatures are not displayed
need restart the world server

**Comment by jasongdove** [comment]
Please provide more details about where you are and which creature you are trying to add.

This sequence tested correctly for me:

```
.tele orgrimmar
.npc add 72501
```

and `.npc del` successfully removes the creature.

**Comment by 5840174** [comment]
just like you did, that's enough
