### ISSUE TITLE
🐛 [Bug] - Player Movement packet structure incorrect

### ISSUE THREAD

**Issue by drikishuk** [Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8#340]
## 🐛 Bug report

Player movement is jittery, potentially due to wrong packet implementation based on Pandaria 5.4.8 core. 
This is only visible when observing other players. 
Apparently this is due to the packet structure being for 5.4.7 and not 5.4.8?

### Expected behavior

Players should move smoothly on other players screens.

**Comment by jasongdove** [comment]
I think this will be fixed by https://github.com/Legends-of-Azeroth/Legends-of-Azeroth-Pandaria-5.4.8/pull/349

**Comment by drikishuk** [comment]
Confirmed Fixed thank you
